update deps
- upto p_timeout@1.0.2 which fixes 'missing field `now`' error

```text
> deno run mod.ts
error: missing field `now` at line 21 column 1
at file:///.../deps.ts:1:51
```